% if a==1,
%     figure('name',num2str(i),'numbertitle','off','pointer','fullcrosshair')
%     u1=uicontrol('style','edit','string',clim(2)); 
%     u2=uicontrol('style','edit','string',clim(1));
%     set(u1,'units','normalized','position',[0.92,0.2,0.05,0.05],...
%         'Callback', ...
%         ['n=str2num(get(gcbo,''string''));', ...
%          'f=get(gcbo,''parent'');', ... 
%          'd=get(f,''userdata'');', ... 
%          'if n>d(3), n=d(3); set(gcbo,''string'',d(3)); end;', ...
%          'clim=get(d(1),''clim'');', ...
%          'set(d(1),''clim'',[clim(1) n]);']);
%     set(u2,'units','normalized','position',[0.92,0.12,0.05,0.05], ...
%         'Callback',...
%         ['n=str2num(get(gcbo,''string''));', ...
%          'f=get(gcbo,''parent'');', ...
%          'd=get(f,''userdata'');', ...
%          'if n<d(2), n=d(2); set(gcbo,''string'',d(2)); end;', ...
%          'clim=get(d(1),''clim'');', ...
%          'set(d(1),''clim'',[n clim(2)]);']);
%      u3=uicontrol('style','text','string','','units','normalized','position',[0.92,0.28,0.05,0.05]);
%      set(gcf,'windowbuttonmotionfcn', ...
%         ['u3=findobj(gcbo,''style'',''text''); ', ...
%          'ax=findobj(gcbo,''type'',''axes''); ', ...
%          'point=get(ax(1),''currentpoint'');', ...
%          'set(u3,''string'',[num2str(fix(100./(2^point(1,2)))/100), '' Hz''])'])
% end;

pln=mod(a,5);
if pln==0, pln=5; end;
if pln==1,
    figure;
end;

ax=subplot(5,1,pln);

n=length(wave);
time=[0:n-1]*dt;

colormap jet
imagesc(time,log2(period),log2(power));

clim=round(get(ax,'clim')*10)/10;
clim=[0 clim(2)];
set(gca,'clim',clim);
set(gca,'YLim',log2([period(1),period(end)]), ...
            ... % 'YDir','reverse', ...
            'YTick',log2(period(:)), ...
            'YTickLabel',fix(100./period)./100)

title(handles.c1{order(a)})        
    
    
    
    
    